---

- name: reboot machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: (ansible_kernel | match("{{linux_kernel_version}}")) == false

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=60 timeout=1200 connect_timeout=15
  when: (ansible_kernel | match("{{linux_kernel_version}}")) == false

- name: display kernel version
  debug: msg="kernel is now {{ansible_kernel}}"
